### ISSUE TITLE
Feature request: max-offset option

### ISSUE THREAD

**Issue by orende** [klarna/kastlex#30]
Kastlex currently only allows querying from a specified starting offset, such as the first offset or the last offset. However, for sufficiently large datasets, the request will timeout before returning any data unless a very recent offset is used. One possible solution for this could be to have an optional max-offset option. For example:

`curl $KASTLEX_SERVER/api/v1/messages/$TOPIC/1/1?max-offset=1000`

This call would return all messages between offset 1 and offset 1000.

With this option, we could use Kastlex to paginate our way through large amounts of messages.

**Comment by zmstone** [comment]
Hi. Which version did you run?

Kastlex requests only 100K bytes from kafka per-request,
if a message at the given offset is larger than 100K the exact ONE message will be fetched.

However, if the given offset points to a compressed batch, the whole batch will be fetched and decompressed in kastlex before responding to HTTP clients.

100K can unlikely cause timeout.
So, it's likely either large message, or a large compressed set.

There is no way to limit the number of messages in kafka requests,
If it's single message size being too large, we can not do much about it except for a larger timeout config.
In case of compression, we can probably make kastlex discard the ones in tail if the total number exceeds limit.

**Comment by id** [comment]
Users can query messages at any offset, and use `min_bytes` and `max_bytes` option
