### ISSUE TITLE
Dockerfile build fails: Could not find "rebar3" to compile dependency :erlzk

### ISSUE THREAD

**Issue by iTaybb** [klarna/kastlex#39]
Looks like the docker image creation fails due to missing dependency "rebar3". It looks like it's really doesn't exist in file mix.lock. Maybe it should be added...

Error:
`Generated logger_file_backend app
==> kastlex
Could not find "rebar3", which is needed to build dependency :erlzk
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] ** (Mix) Could not find "rebar3" to compile dependency :erlzk, please ensure "rebar3" is available
The command '/bin/sh -c mix compile' returned a non-zero code: 1
`

**Comment by id** [comment]
rebar3 is not a project dependency, it's a build tool which needs to be installed locally via `mix local.rebar --force`

**Comment by iTaybb** [comment]
Sorry, forgot to mention I was talking about the Dockerfile.
It seems like `mix local.rebar --force` should be added between lines 8 and 9 in the Dockerfile.

**Comment by id** [comment]
This command worked just fine, tested a minute ago: `docker build .`

**Comment by id** [comment]
No, sorry, you are right. I had cached stuff. Fixing.
