### ISSUE TITLE
Allow content-type application/json

### ISSUE THREAD

**Issue by iTaybb** [klarna/kastlex#42]
At the moment, the api/v1/messages api (and possible more?) doesn't support application/json mimetypes.
Kafka messages will often be json types, so it makes sense to allow application/json mimetype.

Kastlex itself doesn't care whether it's json or not. But there's a universal plug parser at lib/kastlex/endpoint.ex that parses the json and passes an empty message to the queue.

**Comment by iTaybb** [comment]
What are you saying about this, @id?

**Comment by id** [comment]
Sure, why not.
